version: 0.2
phases:
  pre_build:
    commands:
      - npm install -g gatsby
  build:
    commands:
      - cp .env.example .env
      - npm install
      - gatsby build
artifacts:
  files:
    - '**/*'
  base-directory: public
